Repository recodehive/Stackoverflow-Analysis, pull requests merged in 2024-06, with the labels that each got.

#265 Updated readme.md #30
  readme.md
Labels: gssoc

#260 Preferred ways to learn coding for each age group
  backlog/PreferredWaysToLearnCoding.ipynb
Labels: gssoc, level1

#266 Remove ide files
  .DS_Store
  .vscode/settings.json
  Data/.DS_Store
  streamlit/__pycache__/functions.cpython-311.pyc
  streamlit/__pycache__/main_analysis.cpython-311.pyc
Labels: gssoc, level1

#269 BUG FIXED
  streamlit/__pycache__/functions.cpython-311.pyc
  streamlit/__pycache__/main_analysis.cpython-311.pyc
  streamlit/functions.py
  streamlit/home.py
Labels: gssoc, level1

#273 Update readme.md for missed points 2
  readme.md
Labels: gssoc, level3

#274 Update readme.md for missed points 3
  readme.md
Labels: gssoc, level3

#277 Fixed streamlit app
  streamlit/__pycache__/functions.cpython-311.pyc
  streamlit/__pycache__/main_analysis.cpython-311.pyc
  streamlit/functions.py
  streamlit/home.py
  streamlit/main_analysis.py
  streamlit/style.css
Labels: gssoc, level1

#280 Added Table of Contents and Back to Top Buttons to README
  readme.md
Labels: gssoc, level1

#292 Enhancement done in the summary section with borders
  streamlit/main_analysis.py
Labels: gssoc, level1

#304 Community Engagement Analysis
  backlog/CommunityEngagementAnalysis_survey_results_public_2018.ipynb
Labels: gssoc, level1

#303 Technology Trends Analysis
  backlog/Technology_Trends_Analysis__survey_results_public_2018.ipynb
Labels: gssoc, level1
