Repository recodehive/Stackoverflow-Analysis, pull requests merged in 2024-05, with the labels that each got.

#34 Create PR_Template.md
  .github/PR_Template.md
Labels: gssoc, level1

#37 Update readme.md
  readme.md
Labels: gssoc

#53 Stack overflow2018 data cleaning
  Stack_Overflow2018.ipynb
Labels: gssoc, level2

#60 Add files via upload
  Stack_Overflow2018 -data visualization.ipynb
Labels: gssoc, level1

#69 docs: update old github repo url with the new one
  PROPOSAL.md
Labels: gssoc

#72 Create greetings.yaml
  .github/workflows/greetings.yaml
Labels: gssoc, level1

#91 Create Contributing.md
  Contributing.md
Labels: gssoc

#66 EDA on stack overflow dataset-2018
  Stack_Overflow2018- correlations and analysis.ipynb
  bit of analysis.png
  bit of anlysis done.png
Labels: gssoc, level2

#96 Added survey analysis of 2023
  Stackoverflow_Survey_Analysis_2023.ipynb
Labels: gssoc, level3

#109 Fixing Issue #107 Learn.md File Index Not Linked
  Learn.md
Labels: gssoc

#122 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: gssoc, level1

#123 Added Community feat template & workflow
  .github/ISSUE_TEMPLATE/invitation.yml
  .github/workflows/invitation.yml
Labels: gssoc, level2

#127 Added link to project wiki in readme.md
  readme.md
Labels: gssoc, level1

#104 Code Added
  backlog/BestProgrammingLanguage-checkpoint.ipynb
Labels: gssoc, level1

#128 Update invitation.yml
  .github/workflows/autocomment-pr-merge.yml
  .github/workflows/invitation.yml
Labels: gssoc, level3

#136 Update invitation.yml
  .github/workflows/invitation.yml
Labels: gssoc, level3

#133 created autocomment-iss-close.yml
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level1

#139 Fixed broken link in readme
  readme.md
Labels: gssoc

#57 Make Issue template more visually appealing. #51
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc, level2

#142 Added requirements.txt and updated .gitignore
  .gitignore
  requirements.txt
  streamlit/__pycache__/functions.cpython-312.pyc
  streamlit/__pycache__/main_analysis.cpython-312.pyc
Labels: gssoc, level1

#147 Update requirements.txt
  requirements.txt
Labels: bug, gssoc, level1

#134 updated readme file
  readme.md
Labels: gssoc, level3

#151 Update invitation.yml
  .github/workflows/invitation.yml
Labels: gssoc, level1

#158 Ready for Deployment: Bug-Free Streamlit App Pull Request
  streamlit/__pycache__/functions.cpython-311.pyc
  streamlit/__pycache__/main_analysis.cpython-311.pyc
  streamlit/functions.py
  streamlit/home.py
  streamlit/main_analysis.py
  streamlit/requirements.txt
  streamlit/style.css
  streamlit/survey_results_sample_2018.csv
  streamlit/survey_results_sample_2019.csv
  streamlit/survey_results_sample_2020.csv
Labels: gssoc, level2

#160 created the documentation for the streamlit webpage
  streamlit/Readme.md
  streamlit/Visualizations/Screenshot.png
  streamlit/Visualizations/annual-salaries.png
  streamlit/Visualizations/cloning-1.png
  streamlit/Visualizations/cloning-2.png
  streamlit/Visualizations/data-scientist-participation.png
  streamlit/Visualizations/desktop.ini
  streamlit/Visualizations/ethenicity.png
  streamlit/Visualizations/geoplot.png
  streamlit/Visualizations/income-vs-gender.png
  streamlit/Visualizations/languages-desired.png
  streamlit/Visualizations/main-interface.png
  streamlit/Visualizations/terminal.png
Labels: enhancement, ⭐goal: addition, gssoc, level3

#251 transferred workflow to support repo
  .github/ISSUE_TEMPLATE/invitation.yml
  .github/workflows/invitation.yml
Labels: bug, gssoc, level1

#165 Update readme.md
  readme.md
Labels: gssoc, level3

#252 Added analysis _2021
  backlog/stackoverflow_analysis_2021.ipynb
Labels: gssoc, level1

#256 Issue in autocommenting on merged pr #255
  .github/workflows/autocomment-pr-merge.yml
Labels: gssoc, level1
